version: '3'

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    hostname: "mongodb"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=admin123
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=paymentFood

volumes:
  mongodb_data:
    driver: local